// Gerado automaticamente pelo sync_images.mjs

export const dynamicImageMap: Record<string, string> = {
  "Abraçadeira Cano Injetor": "/catalogo-pronto/Abraçadeira Cano Injetor.jpg",
  "Abraçadeira para Canos": "/catalogo-pronto/Abraçadeira para Canos.jpg",
  "Acessórios Micro Retífica": "/catalogo-pronto/Acessórios Micro Retífica.jpg",
  "Acessórios para Máquinas Elétricas": "/catalogo-pronto/Acessórios para Máquinas Elétricas.jpg",
  "Acessórios Pneumático": "/catalogo-pronto/Acessórios Pneumático.jpg",
  "Acessórios": "/catalogo-pronto/Acessórios.jpg",
  "Alavanca Plástica": "/catalogo-pronto/Alavanca Plástica.jpg",
  "Alavancas": "/catalogo-pronto/Alavancas.jpg",
  "Alicate de Pressão": "/catalogo-pronto/Alicate de Pressão.jpg",
  "Alicate de Trava": "/catalogo-pronto/Alicate de Trava.jpg",
  "Alicate Descascador": "/catalogo-pronto/Alicate Descascador.jpg",
  "Alicate para Abraçadeiras": "/catalogo-pronto/Alicate para Abraçadeiras.jpg",
  "Alicates": "/catalogo-pronto/Alicates.jpg",
  "Alça": "/catalogo-pronto/Alça.jpg",
  "Anel de Retenção": "/catalogo-pronto/Anel de Retenção.jpg",
  " Sapatilha": "/catalogo-pronto/Anilha / Sapatilha.jpg",
  "Anilha / Sapatilha": "/catalogo-pronto/Anilha / Sapatilha.jpg",
  "Aparador de Grama": "/catalogo-pronto/Aparador de Grama.jpg",
  "Aplicador Rosca Postiça": "/catalogo-pronto/Aplicador Rosca Postiça.jpg",
  "Arco de Serra": "/catalogo-pronto/Arco de Serra.jpg",
  "Arruela de Alumínio": "/catalogo-pronto/Arruela de Alumínio.jpg",
  "Arruela de Cabeçote": "/catalogo-pronto/Arruela de Cabeçote.jpg",
  "Arruela de Cobre": "/catalogo-pronto/Arruela de Cobre.jpg",
  "Arruela de Encosto": "/catalogo-pronto/Arruela de Encosto.jpg",
  "Arruela de Fibra": "/catalogo-pronto/Arruela de Fibra.jpg",
  "Arruela de Pressão": "/catalogo-pronto/Arruela de Pressão.jpg",
  "Arruela Dentada": "/catalogo-pronto/Arruela Dentada.jpg",
  "Arruela Lisa": "/catalogo-pronto/Arruela Lisa.jpg",
  "Arruela Ondulada": "/catalogo-pronto/Arruela Ondulada.jpg",
  "Arruelas": "/catalogo-pronto/Arruelas.jpg",
  "Aspirador de Pó": "/catalogo-pronto/Aspirador de Pó.jpg",
  "Automotivos": "/catalogo-pronto/Automotivos.jpg",
  "Avental": "/catalogo-pronto/Avental.jpg",
  "Aço": "/catalogo-pronto/Aço.jpg",
  "Bandejas Magnética": "/catalogo-pronto/Bandejas Magnética.jpg",
  "Barra Roscada": "/catalogo-pronto/Barra Roscada.jpg",
  "Bico Encher Pneu": "/catalogo-pronto/Bico Encher Pneu.jpg",
  "Bico Injetor": "/catalogo-pronto/Bico Injetor.jpg",
  " Pulverizador": "/catalogo-pronto/Bico Limpeza / Pulverizador.jpg",
  "Bico Limpeza / Pulverizador": "/catalogo-pronto/Bico Limpeza / Pulverizador.jpg",
  "Bolsa de Cintura": "/catalogo-pronto/Bolsa de Cintura.jpg",
  "Bomba Abastecimento": "/catalogo-pronto/Bomba Abastecimento.jpg",
  "Bombas de Graxa": "/catalogo-pronto/Bombas de Graxa.jpg",
  "Borracha": "/catalogo-pronto/Borracha.jpg",
  "Botina": "/catalogo-pronto/Botina.jpg",
  "Botões": "/catalogo-pronto/Botões.jpg",
  "Broca para Aço": "/catalogo-pronto/Broca para Aço.jpg",
  "Broca para Madeira": "/catalogo-pronto/Broca para Madeira.jpg",
  "Broca Vídea": "/catalogo-pronto/Broca Vídea.jpg",
  "Buchas": "/catalogo-pronto/Buchas.jpg",
  "Bujão Carter": "/catalogo-pronto/Bujão Carter.jpg",
  "Cabo de Aço": "/catalogo-pronto/Cabo de Aço.jpg",
  " Soquetes": "/catalogo-pronto/Cabo de Força P/ Soquetes.jpg",
  "Cabo de Força P/ Soquetes": "/catalogo-pronto/Cabo de Força P/ Soquetes.jpg",
  "Cadeados": "/catalogo-pronto/Cadeados.jpg",
  "Caixa de Ferramentas": "/catalogo-pronto/Caixa de Ferramentas.jpg",
  "Calibrador de Pneu": "/catalogo-pronto/Calibrador de Pneu.jpg",
  "Calota Cubo": "/catalogo-pronto/Calota Cubo.jpg",
  "Canaleta": "/catalogo-pronto/Canaleta.jpg",
  "Capacete": "/catalogo-pronto/Capacete.jpg",
  "Carregador de Bateria": "/catalogo-pronto/Carregador de Bateria.jpg",
  "Carro de Ferramentas": "/catalogo-pronto/Carro de Ferramentas.jpg",
  "Castelo": "/catalogo-pronto/Castelo.jpg",
  "Catraca para Amarração": "/catalogo-pronto/Catraca para Amarração.jpg",
  "Catraca Pneumática": "/catalogo-pronto/Catraca Pneumática.jpg",
  "Catraca Reversível": "/catalogo-pronto/Catraca Reversível.jpg",
  "Chave Allen": "/catalogo-pronto/Chave Allen.jpg",
  " L": "/catalogo-pronto/Chave Biela / L.jpg",
  "Chave Biela / L": "/catalogo-pronto/Chave Biela / L.jpg",
  "Chave Canhão": "/catalogo-pronto/Chave Canhão.jpg",
  "Chave de Impacto Pneumática": "/catalogo-pronto/Chave de Impacto Pneumática.jpg",
  "Chave de Impacto": "/catalogo-pronto/Chave de Impacto.jpg",
  "Chave de Roda": "/catalogo-pronto/Chave de Roda.jpg",
  "Chave Fecho": "/catalogo-pronto/Chave Fecho.jpg",
  " Cano": "/catalogo-pronto/Chave Grifo / Cano.jpg",
  "Chave Grifo / Cano": "/catalogo-pronto/Chave Grifo / Cano.jpg",
  " Ajustável": "/catalogo-pronto/Chave Inglesa / Ajustável.jpg",
  "Chave Inglesa / Ajustável": "/catalogo-pronto/Chave Inglesa / Ajustável.jpg",
  "Chave Saca Filtro": "/catalogo-pronto/Chave Saca Filtro.jpg",
  "Chave Torx": "/catalogo-pronto/Chave Torx.jpg",
  "Chaves Combinada": "/catalogo-pronto/Chaves Combinada.jpg",
  " Frezada": "/catalogo-pronto/Chaves Estrela / Frezada.jpg",
  "Chaves Estrela / Frezada": "/catalogo-pronto/Chaves Estrela / Frezada.jpg",
  "Chaves Fenda e Philips": "/catalogo-pronto/Chaves Fenda e Philips.jpg",
  " Boca": "/catalogo-pronto/Chaves Fixas / Boca.jpg",
  "Chaves Fixas / Boca": "/catalogo-pronto/Chaves Fixas / Boca.jpg",
  "Chavetas": "/catalogo-pronto/Chavetas.jpg",
  "Cintos": "/catalogo-pronto/Cintos.jpg",
  "Clips para Cabo de Aço": "/catalogo-pronto/Clips para Cabo de Aço.jpg",
  "Colas": "/catalogo-pronto/Colas.jpg",
  "Compressor Portátil": "/catalogo-pronto/Compressor Portátil.jpg",
  "Compressores": "/catalogo-pronto/Compressores.jpg",
  "Cone": "/catalogo-pronto/Cone.jpg",
  "Cordas": "/catalogo-pronto/Cordas.jpg",
  "Corrente Plástica": "/catalogo-pronto/Corrente Plástica.jpg",
  "Corrente": "/catalogo-pronto/Corrente.jpg",
  "Cortador de Piso": "/catalogo-pronto/Cortador de Piso.jpg",
  "Cortador de Vidro": "/catalogo-pronto/Cortador de Vidro.jpg",
  "Cossinete": "/catalogo-pronto/Cossinete.jpg",
  "Cupilhas": "/catalogo-pronto/Cupilhas.jpg",
  "Desengraxantes": "/catalogo-pronto/Desengraxantes.jpg",
  "Disco de Corte": "/catalogo-pronto/Disco de Corte.jpg",
  "Disco de Desbaste": "/catalogo-pronto/Disco de Desbaste.jpg",
  "Disco de Lixa": "/catalogo-pronto/Disco de Lixa.jpg",
  "Disco Flap": "/catalogo-pronto/Disco Flap.jpg",
  "Disco Serra Circular": "/catalogo-pronto/Disco Serra Circular.jpg",
  "Disco Serra Mármore": "/catalogo-pronto/Disco Serra Mármore.jpg",
  "Dobradiças Plásticas": "/catalogo-pronto/Dobradiças Plásticas.jpg",
  "Duplas": "/catalogo-pronto/Duplas.jpg",
  " MMA": "/catalogo-pronto/Eletrodo / MMA.jpg",
  "Eletrodo / MMA": "/catalogo-pronto/Eletrodo / MMA.jpg",
  "Elevação": "/catalogo-pronto/Elevação.jpg",
  "Encolhedor de Mola": "/catalogo-pronto/Encolhedor de Mola.jpg",
  "Engate Rápido": "/catalogo-pronto/Engate Rápido.jpg",
  "Engraxadeira": "/catalogo-pronto/Engraxadeira.jpg",
  "Escova Limpeza Detalhada": "/catalogo-pronto/Escova Limpeza Detalhada.jpg",
  "Escova para Limpeza": "/catalogo-pronto/Escova para Limpeza.jpg",
  "Escovas": "/catalogo-pronto/Escovas.jpg",
  "Esfera de Aço": "/catalogo-pronto/Esfera de Aço.jpg",
  "Esguicho de Água": "/catalogo-pronto/Esguicho de Água.jpg",
  "Esmerilhadeira": "/catalogo-pronto/Esmerilhadeira.jpg",
  "Especiais": "/catalogo-pronto/Especiais.jpg",
  "Espátulas de Aço": "/catalogo-pronto/Espátulas de Aço.jpg",
  "Esquadro Magnético": "/catalogo-pronto/Esquadro Magnético.jpg",
  "Esteira para Mecânico": "/catalogo-pronto/Esteira para Mecânico.jpg",
  " Cabo": "/catalogo-pronto/Esticador P/ Cabo.jpg",
  "Esticador P/ Cabo": "/catalogo-pronto/Esticador P/ Cabo.jpg",
  "Estilete": "/catalogo-pronto/Estilete.jpg",
  "Extensão Elétrica": "/catalogo-pronto/Extensão Elétrica.jpg",
  "Fechaduras Elétrica": "/catalogo-pronto/Fechaduras Elétrica.jpg",
  "Ferramentas a Bateria": "/catalogo-pronto/Ferramentas a Bateria.jpg",
  "Ferramentas a Combustão": "/catalogo-pronto/Ferramentas a Combustão.jpg",
  "Ferramentas Automotivas": "/catalogo-pronto/Ferramentas Automotivas.jpg",
  "Ferramentas de Medição": "/catalogo-pronto/Ferramentas de Medição.jpg",
  "Ferramentas Elétricas": "/catalogo-pronto/Ferramentas Elétricas.jpg",
  "Ferramentas Isoladas": "/catalogo-pronto/Ferramentas Isoladas.jpg",
  "Ferramentas Manuais": "/catalogo-pronto/Ferramentas Manuais.jpg",
  "Ferramentas Pneumáticas": "/catalogo-pronto/Ferramentas Pneumáticas.jpg",
  "Ferramentas": "/catalogo-pronto/Ferramentas.jpg",
  "Ferro": "/catalogo-pronto/Ferro.jpg",
  "Fibra Abrasiva": "/catalogo-pronto/Fibra Abrasiva.jpg",
  "Fita Dupla Face": "/catalogo-pronto/Fita Dupla Face.jpg",
  "Fita para Amarração": "/catalogo-pronto/Fita para Amarração.jpg",
  "Fita Zebrada": "/catalogo-pronto/Fita Zebrada.jpg",
  "Flangeadas": "/catalogo-pronto/Flangeadas.jpg",
  "Fluxo de Solda": "/catalogo-pronto/Fluxo de Solda.jpg",
  " Frisadeira": "/catalogo-pronto/Fresadora / Frisadeira.jpg",
  "Fresadora / Frisadeira": "/catalogo-pronto/Fresadora / Frisadeira.jpg",
  "Fresas": "/catalogo-pronto/Fresas.jpg",
  "Funilaria": "/catalogo-pronto/Funilaria.jpg",
  "Furadeira de Bancada": "/catalogo-pronto/Furadeira de Bancada.jpg",
  "Furadeira Pneumática": "/catalogo-pronto/Furadeira Pneumática.jpg",
  "Furadeira": "/catalogo-pronto/Furadeira.jpg",
  "Galão de Gasolina": "/catalogo-pronto/Galão de Gasolina.jpg",
  "Gancho Olhal": "/catalogo-pronto/Gancho Olhal.jpg",
  "Gaveteiros": "/catalogo-pronto/Gaveteiros.jpg",
  "Gerador": "/catalogo-pronto/Gerador.jpg",
  " Pinador Elétrico": "/catalogo-pronto/Grampeador / Pinador Elétrico.jpg",
  "Grampeador / Pinador Elétrico": "/catalogo-pronto/Grampeador / Pinador Elétrico.jpg",
  "Grampeador Pneumático": "/catalogo-pronto/Grampeador Pneumático.jpg",
  "Grampo Sargento": "/catalogo-pronto/Grampo Sargento.jpg",
  "Grampo Tapeceiro": "/catalogo-pronto/Grampo Tapeceiro.jpg",
  "Grampo Tensor": "/catalogo-pronto/Grampo Tensor.jpg",
  "Graxas": "/catalogo-pronto/Graxas.jpg",
  "Graxeiras": "/catalogo-pronto/Graxeiras.jpg",
  "Guincho Elétrico": "/catalogo-pronto/Guincho Elétrico.jpg",
  "image": "/catalogo-pronto/image.jpg",
  "Inoxidável": "/catalogo-pronto/Inoxidável.jpg",
  " Torno": "/catalogo-pronto/Inserto P/ Torno.jpg",
  "Inserto P/ Torno": "/catalogo-pronto/Inserto P/ Torno.jpg",
  "Intercooler": "/catalogo-pronto/Intercooler.jpg",
  "Jogo Allen": "/catalogo-pronto/Jogo Allen.jpg",
  "Jogo Chave Combinada": "/catalogo-pronto/Jogo Chave Combinada.jpg",
  "Jogo Chave Fixa": "/catalogo-pronto/Jogo Chave Fixa.jpg",
  "Jogo Chave Frezada": "/catalogo-pronto/Jogo Chave Frezada.jpg",
  " Phillips": "/catalogo-pronto/Jogo Fenda / Phillips.jpg",
  "Jogo Fenda / Phillips": "/catalogo-pronto/Jogo Fenda / Phillips.jpg",
  "Jogo Soquete": "/catalogo-pronto/Jogo Soquete.jpg",
  "Kit Acessórios para Limpeza": "/catalogo-pronto/Kit Acessórios para Limpeza.jpg",
  "Kit de Ferramentas": "/catalogo-pronto/Kit de Ferramentas.jpg",
  "Kit Remendo": "/catalogo-pronto/Kit Remendo.jpg",
  " Bits": "/catalogo-pronto/Kits de Pontas / Bits.jpg",
  "Kits de Pontas / Bits": "/catalogo-pronto/Kits de Pontas / Bits.jpg",
  "Lanternas": "/catalogo-pronto/Lanternas.jpg",
  "Lavadora de Alta Pressão": "/catalogo-pronto/Lavadora de Alta Pressão.jpg",
  "Lima": "/catalogo-pronto/Lima.jpg",
  "Lixadeira e Politriz": "/catalogo-pronto/Lixadeira e Politriz.jpg",
  "Lixas": "/catalogo-pronto/Lixas.jpg",
  "Luvas": "/catalogo-pronto/Luvas.jpg",
  "Lâminas de Serra": "/catalogo-pronto/Lâminas de Serra.jpg",
  "Lâmpadas": "/catalogo-pronto/Lâmpadas.jpg",
  "Macho Manual de Rosca": "/catalogo-pronto/Macho Manual de Rosca.jpg",
  "Maleta e Bolsa de Ferramentas": "/catalogo-pronto/Maleta e Bolsa de Ferramentas.jpg",
  "Mandril": "/catalogo-pronto/Mandril.jpg",
  "Mangote": "/catalogo-pronto/Mangote.jpg",
  "Manilha": "/catalogo-pronto/Manilha.jpg",
  "Manopla": "/catalogo-pronto/Manopla.jpg",
  "Manta Adesiva Asfáltica": "/catalogo-pronto/Manta Adesiva Asfáltica.jpg",
  "Manípulos": "/catalogo-pronto/Manípulos.jpg",
  "Manômetros": "/catalogo-pronto/Manômetros.jpg",
  "Marretas": "/catalogo-pronto/Marretas.jpg",
  "Martelete Elétrico": "/catalogo-pronto/Martelete Elétrico.jpg",
  "Martelos": "/catalogo-pronto/Martelos.jpg",
  "Maçaricos": "/catalogo-pronto/Maçaricos.jpg",
  "Medidor de Pressão": "/catalogo-pronto/Medidor de Pressão.jpg",
  "Medição": "/catalogo-pronto/Medição.jpg",
  "Micrômetro": "/catalogo-pronto/Micrômetro.jpg",
  "MIG": "/catalogo-pronto/MIG.jpg",
  "Misturador de Tinta": "/catalogo-pronto/Misturador de Tinta.jpg",
  "Moitão": "/catalogo-pronto/Moitão.jpg",
  "Molas": "/catalogo-pronto/Molas.jpg",
  "Moto Esmeril": "/catalogo-pronto/Moto Esmeril.jpg",
  "Multiferramenta Oscilante": "/catalogo-pronto/Multiferramenta Oscilante.jpg",
  "Máquina de Solda": "/catalogo-pronto/Máquina de Solda.jpg",
  "Máscaras": "/catalogo-pronto/Máscaras.jpg",
  "Nylon": "/catalogo-pronto/Nylon.jpg",
  "Olhal Hidráulico": "/catalogo-pronto/Olhal Hidráulico.jpg",
  "Olhal para Cabo Aço": "/catalogo-pronto/Olhal para Cabo Aço.jpg",
  "Pad Pintura": "/catalogo-pronto/Pad Pintura.jpg",
  " Chumbador": "/catalogo-pronto/Parabolt / Chumbador.jpg",
  "Parabolt / Chumbador": "/catalogo-pronto/Parabolt / Chumbador.jpg",
  "Parafusadeira de Precisão": "/catalogo-pronto/Parafusadeira de Precisão.jpg",
  "Parafusadeiras": "/catalogo-pronto/Parafusadeiras.jpg",
  "Parafuso Allen Cabeça Chata": "/catalogo-pronto/Parafuso Allen Cabeça Chata.jpg",
  "Parafuso Allen Cilíndrica MM": "/catalogo-pronto/Parafuso Allen Cilíndrica MM.jpg",
  "Parafuso Allen Cilíndrica Polegada": "/catalogo-pronto/Parafuso Allen Cilíndrica Polegada.jpg",
  "Parafuso Allen Sem Cabeça": "/catalogo-pronto/Parafuso Allen Sem Cabeça.jpg",
  "Parafuso Allen": "/catalogo-pronto/Parafuso Allen.jpg",
  "Parafuso Cardan": "/catalogo-pronto/Parafuso Cardan.jpg",
  "Parafuso e Porca de Roda": "/catalogo-pronto/Parafuso e Porca de Roda.jpg",
  "Parafuso Francês": "/catalogo-pronto/Parafuso Francês.jpg",
  "Parafuso Oco": "/catalogo-pronto/Parafuso Oco.jpg",
  "Parafuso Sextavado": "/catalogo-pronto/Parafuso Sextavado.jpg",
  "Parafusos Automotivos": "/catalogo-pronto/Parafusos Automotivos.jpg",
  "Parafusos Brocante": "/catalogo-pronto/Parafusos Brocante.jpg",
  "Parafusos de Cabeçote": "/catalogo-pronto/Parafusos de Cabeçote.jpg",
  "Parafusos e Porcas Geral": "/catalogo-pronto/Parafusos e Porcas Geral.jpg",
  "Parafusos Fendados": "/catalogo-pronto/Parafusos Fendados.jpg",
  "Parafusos Inoxidáveis": "/catalogo-pronto/Parafusos Inoxidáveis.jpg",
  "Parafusos Moto": "/catalogo-pronto/Parafusos Moto.jpg",
  "Parafusos": "/catalogo-pronto/Parafusos.jpg",
  "PARAFUSOS": "/catalogo-pronto/icon-parafusos.png",
  "Pasta Abrasiva": "/catalogo-pronto/Pasta Abrasiva.jpg",
  "Pegador Magnético": "/catalogo-pronto/Pegador Magnético.jpg",
  "Pincel": "/catalogo-pronto/Pincel.jpg",
  "Pino de Centro": "/catalogo-pronto/Pino de Centro.jpg",
  "Pino Elástico": "/catalogo-pronto/Pino Elástico.jpg",
  "Pistola de Pintura Pneumática": "/catalogo-pronto/Pistola de Pintura Pneumática.jpg",
  "Pistola de Pintura": "/catalogo-pronto/Pistola de Pintura.jpg",
  "Pistola Jato de Areia": "/catalogo-pronto/Pistola Jato de Areia.jpg",
  " Carvão": "/catalogo-pronto/Plasma / Carvão.jpg",
  "Plasma / Carvão": "/catalogo-pronto/Plasma / Carvão.jpg",
  "Policorte": "/catalogo-pronto/Policorte.jpg",
  "Politriz": "/catalogo-pronto/Politriz.jpg",
  "Ponta Montada": "/catalogo-pronto/Ponta Montada.jpg",
  "Ponteira Bits": "/catalogo-pronto/Ponteira Bits.jpg",
  "Porta Bedame": "/catalogo-pronto/Porta Bedame.jpg",
  "Porta Eletrodo": "/catalogo-pronto/Porta Eletrodo.jpg",
  "Porta Ferramenta Inserto": "/catalogo-pronto/Porta Ferramenta Inserto.jpg",
  "Presilhas Plástica": "/catalogo-pronto/Presilhas Plástica.jpg",
  "Primer": "/catalogo-pronto/Primer.jpg",
  "Prisioneiro": "/catalogo-pronto/Prisioneiro.jpg",
  "Protetor Auricular": "/catalogo-pronto/Protetor Auricular.jpg",
  "Protetor Facial": "/catalogo-pronto/Protetor Facial.jpg",
  "Protetor Solar": "/catalogo-pronto/Protetor Solar.jpg",
  "Pulverizador de Sabão": "/catalogo-pronto/Pulverizador de Sabão.jpg",
  "Pé de Cabra": "/catalogo-pronto/Pé de Cabra.jpg",
  "Pé Nivelador": "/catalogo-pronto/Pé Nivelador.jpg",
  "Quebra Galho": "/catalogo-pronto/Quebra Galho.jpg",
  "Radial": "/catalogo-pronto/Radial.jpg",
  "Rebater": "/catalogo-pronto/Rebater.jpg",
  "Rebitador": "/catalogo-pronto/Rebitador.jpg",
  "Rebolo": "/catalogo-pronto/Rebolo.jpg",
  "Registro de Gás": "/catalogo-pronto/Registro de Gás.jpg",
  "Regulador de Pressão": "/catalogo-pronto/Regulador de Pressão.jpg",
  "Relógio Comparador": "/catalogo-pronto/Relógio Comparador.jpg",
  " Pop": "/catalogo-pronto/Repuxo / Pop.jpg",
  "Repuxo / Pop": "/catalogo-pronto/Repuxo / Pop.jpg",
  "Retificadeiras Elétricas": "/catalogo-pronto/Retificadeiras Elétricas.jpg",
  "Retificadeiras": "/catalogo-pronto/Retificadeiras.jpg",
  "Retificador Diamantado": "/catalogo-pronto/Retificador Diamantado.jpg",
  "Rodos": "/catalogo-pronto/Rodos.jpg",
  " Suplemento": "/catalogo-pronto/Rosca Postiça / Suplemento.jpg",
  "Rosca Postiça / Suplemento": "/catalogo-pronto/Rosca Postiça / Suplemento.jpg",
  "Rosca Soberba": "/catalogo-pronto/Rosca Soberba.jpg",
  "Roçadeira": "/catalogo-pronto/Roçadeira.jpg",
  "Roçadeiras": "/catalogo-pronto/Roçadeiras.jpg",
  "Saca Gaxetas": "/catalogo-pronto/Saca Gaxetas.jpg",
  "Saca Polia": "/catalogo-pronto/Saca Polia.jpg",
  "Saco Coletor de Pó": "/catalogo-pronto/Saco Coletor de Pó.jpg",
  "Sangrias": "/catalogo-pronto/Sangrias.jpg",
  "Scanner": "/catalogo-pronto/Scanner.jpg",
  "Serra Copo Aço": "/catalogo-pronto/Serra Copo Aço.jpg",
  "Serra Copo Madeira": "/catalogo-pronto/Serra Copo Madeira.jpg",
  "Serra Copo Vídea": "/catalogo-pronto/Serra Copo Vídea.jpg",
  "Serra de Esquadria": "/catalogo-pronto/Serra de Esquadria.jpg",
  "Serra Elétrica": "/catalogo-pronto/Serra Elétrica.jpg",
  "Serra Mármore": "/catalogo-pronto/Serra Mármore.jpg",
  "Serra Tico-Tico": "/catalogo-pronto/Serra Tico-Tico.jpg",
  "Sextavado Flangeado Aço 10.9": "/catalogo-pronto/Sextavado Flangeado Aço 10.9.jpg",
  "Sextavado Flangeado Aço 8.8": "/catalogo-pronto/Sextavado Flangeado Aço 8.8.jpg",
  "Sextavado Milímetro Aço 10.9": "/catalogo-pronto/Sextavado Milímetro Aço 10.9.jpg",
  "Sextavado Milímetro Aço 8.8": "/catalogo-pronto/Sextavado Milímetro Aço 8.8.jpg",
  "Sextavado Polegada Aço Gr 5 8.8": "/catalogo-pronto/Sextavado Polegada Aço Gr 5 8.8.jpg",
  "Silicones": "/catalogo-pronto/Silicones.jpg",
  "Soprador Elétrico": "/catalogo-pronto/Soprador Elétrico.jpg",
  "Soprador Térmico": "/catalogo-pronto/Soprador Térmico.jpg",
  "Soprador": "/catalogo-pronto/Soprador.jpg",
  "Soquetes": "/catalogo-pronto/Soquetes.jpg",
  "Suporte Disco de Borracha": "/catalogo-pronto/Suporte Disco de Borracha.jpg",
  "Suportes": "/catalogo-pronto/Suportes.jpg",
  "Talha de Elevação": "/catalogo-pronto/Talha de Elevação.jpg",
  "Ponteiras": "/catalogo-pronto/Talhadeiras/Ponteiras.jpg",
  "Talhadeiras/Ponteiras": "/catalogo-pronto/Talhadeiras/Ponteiras.jpg",
  "Talhadeiras": "/catalogo-pronto/Talhadeiras.jpg",
  "Terminais Articulados": "/catalogo-pronto/Terminais Articulados.jpg",
  "Thinner": "/catalogo-pronto/Thinner.jpg",
  "TIG": "/catalogo-pronto/TIG.jpg",
  "Tinta Spray": "/catalogo-pronto/Tinta Spray.jpg",
  "Tipo Fita": "/catalogo-pronto/Tipo Fita.jpg",
  "Tipo Janela": "/catalogo-pronto/Tipo Janela.jpg",
  "Tipo Norma": "/catalogo-pronto/Tipo Norma.jpg",
  "Tipo U": "/catalogo-pronto/Tipo U.jpg",
  "Tirfor": "/catalogo-pronto/Tirfor.jpg",
  "index.d": "/catalogo-pronto/tmp/dist/index.d.mts",
  "tmp/dist/index.d": "/catalogo-pronto/tmp/dist/index.d.mts",
  "Toalhas de Microfibra": "/catalogo-pronto/Toalhas de Microfibra.jpg",
  "Tochas de Solda": "/catalogo-pronto/Tochas de Solda.jpg",
  "Tomadas 12V": "/catalogo-pronto/Tomadas 12V.jpg",
  "Torquímetro": "/catalogo-pronto/Torquímetro.jpg",
  "Touca Soldador": "/catalogo-pronto/Touca Soldador.jpg",
  "Trava Aranha": "/catalogo-pronto/Trava Aranha.jpg",
  "Trava Externa": "/catalogo-pronto/Trava Externa.jpg",
  "Trava Interna": "/catalogo-pronto/Trava Interna.jpg",
  "Travante Torque": "/catalogo-pronto/Travante Torque.jpg",
  "Travantes Nylon": "/catalogo-pronto/Travantes Nylon.jpg",
  "Trena a Laser": "/catalogo-pronto/Trena a Laser.jpg",
  "Trenas": "/catalogo-pronto/Trenas.jpg",
  "Tubo Espaguete Isolante": "/catalogo-pronto/Tubo Espaguete Isolante.jpg",
  "Tucho": "/catalogo-pronto/Tucho.jpg",
  "Tupias e Plainas": "/catalogo-pronto/Tupias e Plainas.jpg",
  "Vaselinas": "/catalogo-pronto/Vaselinas.jpg",
  "Vassouras": "/catalogo-pronto/Vassouras.jpg",
  "Vazador": "/catalogo-pronto/Vazador.jpg",
  "Veda-Choque": "/catalogo-pronto/Veda-Choque.jpg",
  "Vibra-Stop": "/catalogo-pronto/Vibra-Stop.jpg",
  "Volante 2 Raios": "/catalogo-pronto/Volante 2 Raios.jpg",
  "Óculos": "/catalogo-pronto/Óculos.jpg",
  "Óleo Automotivo": "/catalogo-pronto/Óleo Automotivo.jpg"
};
